services:
  workspace:
    build: .
    command: sleep infinity
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: otel-genai-practice
      OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT: true
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888